"AZURE_OPENAI_API_KEY" = "655f425df0ea4caa97c1ec3f7f88adaf"
"AZURE_OPENAI_ENDPOINT" = "https://candaeastaa.openai.azure.com/"


[passwords]
# Follow the rule: username = "password"
tony_feng = "pcai"
meghayu_dave = "pcai"